src/main/urls.py
from django.urls import path 
from main import views


urlpatterns = [
    path("overview/", views.overview, name="overview"),
    path(
        "hx-get-log-details/<str:cheer_log_id>/", 
        views.hx_get_log_details, 
        name="hx-get-log-details"
    ),
    path(
        "hx-send-sfx-to-consumers/<str:sfx_request_id>/", 
        views.hx_send_sfx_to_consumers, 
        name="hx-send-sfx-to-consumers"
    ),
    path(
        "hx-generate-sfx/", 
        views.hx_generate_sfx, 
        name="hx-generate-sfx"
    ),
    path(
        "hx-sfx-list-for-cheer-log/<str:cheer_log_id>/",
        views.hx_sfx_list_for_cheer_log,
        name="hx-sfx-list-for-cheer-log"
    ),
    path(
        "alert-preferences/",
        views.alert_preferences_form,
        name="alert-preferences"
    ),
    path(
        "billing/",
        views.billing_view,
        name="billing"
    )
]

src/twitch_bot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from main import views
from .views import login_template, home, privacy_policy, terms_of_service, refund_policy
from billing import views as billing_views
urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path("login/", login_template, name="login"),
    path("hooks/twitch/events/", views.twitch_eventsub_callback, name="twitch-hook"),
    path("hooks/lemon/events/", billing_views.lemon_webhook, name="lemon-webhook"),
    path("overlay/<str:user_id>/", views.broadcaster_overlay, name="overlay"),
    path("dashboard/", include(("main.urls", "main"), namespace="dashboard")),
    path("legal/refunds-policy/", refund_policy, name="refunds-policy"),
    path("legal/privacy-policy/", privacy_policy, name="privacy-policy"),
    path("legal/terms-of-service/", terms_of_service, name="terms-of-service"),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser
from billing.constants import SubscriptionPlanOptions
# Create your models here.



class Broadcaster(AbstractUser):
    id = models.UUIDField(
        default=uuid.uuid4,
        primary_key=True,
        editable=False
    )
    lemon_customer_id = models.TextField(null=True, blank=True)
    lemon_subscription_item_id = models.TextField(null=True, blank=True)
    max_free_runs = models.IntegerField(default=15)
    billing_plan = models.CharField(
        max_length=10, 
        choices=SubscriptionPlanOptions.PLANS_LIST, 
        default=SubscriptionPlanOptions.PLAN_DEFAULT
    )

    @property
    def has_lemon_billing_setup(self):
        return bool(self.lemon_customer_id) and bool(self.lemon_subscription_item_id)

src/main/models.py
import uuid
import os 
import logging

from django.db import models
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from twitch_bot.exceptions import TwitchEventSubCreationFailed

from .constants import (
    SOUND_EFFECT_REQUEST_STATUS_OPTIONS, 
    CHEER_EVENT_LOG_STATUS_OPTIONS,
    TWITCH_CHEER_EXTERNAL_REFERENCE,
    NEW_STATUS,
    DONE_STATUS
)
from allauth.account.signals import user_signed_up

from twitch_bot.client import TwitchClient

logger = logging.getLogger('django')

class CheerEventLogEntry(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4, 
        primary_key=True, 
        editable=False
    )
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)
    internal_broadcaster_user = models.ForeignKey(
        get_user_model(), 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True
    )
    status = models.CharField(choices=CHEER_EVENT_LOG_STATUS_OPTIONS, default=NEW_STATUS, max_length=1)
    #twitch notification fields
    twitch_message_id = models.TextField(null = False)
    is_anonymous = models.BooleanField(default=False)
    user_id = models.CharField(max_length=50, null=True, blank=True)
    user_login = models.CharField(max_length=150, null=True, blank=True)
    user_name = models.CharField(max_length=150, null=True, blank=True)
    broadcaster_user_id = models.CharField(max_length=50)
    broadcaster_user_login = models.CharField(max_length=150)
    broadcaster_user_name = models.CharField(max_length=150)
    message = models.TextField()
    bits = models.IntegerField(default=0)

    def __str__(self):
        return str(self.broadcaster_user_name)

    class Meta:
        ordering = ["-timestamp"]

#if we want to support more alert types, a unique model for preferences based on each type might be necessary. for now this is all we need. 
class AlertPreferences(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4, 
        primary_key=True, 
        editable=False
    )
    user = models.OneToOneField(
        get_user_model(), 
        on_delete=models.CASCADE
    )
    match_command = models.BooleanField(default=False)
    command_string = models.CharField(
        max_length=20, 
        default="$fx"
    )
    auto_generate = models.BooleanField(default=True)
    auto_play = models.BooleanField (default=True)
    match_bits = models.BooleanField(
        default=True, 
        help_text="If enabled, the match ammount has to be exact to generate a sfx. Otherwise, anything over the set bit ammount will generate a sfx.")
    min_bits = models.IntegerField(default=200)
    cheer_eventsub_id = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username + " preferences"

class SoundEffectRequest(models.Model):

    def upload_sfx_file(instance, filename):
        return os.path.join(
            "sfx_files", 
            str(instance.cheer_event_log.internal_broadcaster_user.id), 
            str(instance.cheer_event_log.id), 
            filename
        )
    
    id = models.UUIDField(
        default=uuid.uuid4, 
        primary_key=True, 
        editable=False
    )
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)
    cheer_event_log = models.ForeignKey(CheerEventLogEntry, on_delete=models.CASCADE)
    status = models.CharField(
        choices=SOUND_EFFECT_REQUEST_STATUS_OPTIONS,
        max_length=1,
        default=NEW_STATUS
    )
    generated_file = models.FileField(upload_to=upload_sfx_file, null=True, blank=True)
    failed_reason = models.TextField(blank=True)
    is_metered = models.BooleanField(default=False)
    usage_record_id = models.TextField(null=True, blank=True)

    @property
    def has_usage_record(self):
        return bool(self.usage_record_id)

    class Meta:
        ordering = ["-timestamp"]


@receiver(user_signed_up)
def create_settings_for_new_user(request, user, **kwargs):
    client = TwitchClient(settings.TWITCH_APP_CLIENT_ID, settings.TWITCH_APP_CLIENT_SECRET)
    socialaccount = user.socialaccount_set.get(provider="twitch") 
    twitch_uid = socialaccount.uid
    try:
        eventsub = client.create_eventsub(TWITCH_CHEER_EXTERNAL_REFERENCE, str(twitch_uid))
        eventsub_id = eventsub["data"][0]["id"]
    except TwitchEventSubCreationFailed:
        logger.error("Twitch Setup: Failed to create eventsub")
        eventsub_id = None
    AlertPreferences.objects.create(user=user, cheer_eventsub_id=eventsub_id)

@receiver(post_save, sender=SoundEffectRequest)    
def update_cheer_log_status(sender, instance, created, *args, **kwargs):
    cheer_log = instance.cheer_event_log

    if cheer_log.status == DONE_STATUS or instance.status == NEW_STATUS:
        return None
    
    cheer_log.status = instance.status
    cheer_log.save()

src/templates/dashboard/partials/alert_preferences_form.html
{% load widget_tweaks %}

<form hx-post="{% url 'dashboard:alert-preferences' %}">
    <h2 class="text-lg font-grotesk text-white pt-5 font-medium">
        General preferences
    </h2>

    <div class="flex justify-between flex-col-reverse md:flex-row gap-2">     
        <div class="md:py-5">
            <p class="text-gray-200 font-grotesk font-medium">Auto generate sound effects</p>
            <p class="text-gray-200 font-grotesk text-sm">
                When enabled the messages that match the set requirements
                will automatically generate a sound effect using the cheer 
                message as a prompt.
            </p>
        </div>

        <label class="inline-flex items-center cursor-pointer pt-5 md:pt-0">
            {% render_field form.auto_generate type="checkbox" class="sr-only peer" %}
           
            <div class="relative w-11 h-6 bg-gray-200 rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all  peer-checked:bg-purple-600 "></div>
        </label>
    </div>

<div class="flex justify-between flex-col-reverse md:flex-row gap-2">
    <div class="pb-5 md:py-5">
        <p class="text-gray-200 font-grotesk font-medium">Auto play on stream</p>
        <p class="text-gray-200 font-grotesk text-sm">
            When enabled the generated sound effects will play in your 
            live stream automatically.
        </p>
    </div>

    <label class="inline-flex items-center cursor-pointer pt-5 md:pt-0">
        {% render_field form.auto_play type="checkbox" class="sr-only peer" %}
        <div class="relative w-11 h-6 bg-gray-200 rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all  peer-checked:bg-purple-600 "></div>
    </label>

</div>

<hr class="border-zinc-800 ">

<h2 class="pt-5 font-grotesk text-lg text-gray-200">Cheer requirements</h2>

<div class="grid grid-cols-1 gap-4 lg:grid-cols-2 lg:gap-8 ">
    <div class="pt-5">
        <label for="bits-input" class="block mb-2 text-sm font-grotesk font-medium text-gray-200 ">Bits ammount</label>
        <div class="relative">
            <div class="absolute inset-y-0 start-0 top-0 flex items-center ps-3.5 pointer-events-none">
                <img src="https://media.tenor.com/izJVS6Wb-lYAAAAi/bits.gif" class="w-5" alt="">
            </div>
            
            {% render_field form.min_bits|add_error_class:"border-red-500"|attr:"required"|attr:"min:1" type="number" class="input-text ps-10" placeholder="200" %}
            
        </div>
        {% if form.min_bits.errors %}<div class="text-sm text-red-500 font-grotesk">{{form.min_bits.errors}}</div>{%endif%}
        <div class="pt-5 flex justify-between">
            <div>
                <p class="text-gray-200 font-medium font-grotesk">Exact ammount match</p>
                <p class="text-gray-200 font-grotesk text-sm">
                    When enabled the cheers must match the set ammount for the 
                    sound effect to be generated. Otherwise, any cheer bigger 
                    than the set value will be used to generate a sound effect.
                </p>
            </div>
            <label class="inline-flex items-center cursor-pointer">
                {% render_field form.match_bits type="checkbox" class="sr-only peer" %}
                <div class="relative w-11 h-6 bg-gray-200 rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all  peer-checked:bg-purple-600 "></div>
            </label>
        </div>
    </div>

    <div class="pt-5">
        <label 
        for="cmd-input" 
        class="block mb-2 text-sm font-grotesk font-medium text-gray-200 ">
            Command
        </label>
        <div class="relative">
            {% render_field form.command_string class="input-text" placeholder="Your custom command"%}
        </div>
        <div class="pt-5 flex justify-between">
            <div>
                <p class="text-gray-200 font-medium font-grotesk">Use command</p>
                <p class="text-gray-200 font-grotesk text-sm">
                    Only messages that start with the specified command will 
                    generate a sound effect.
                </p>
            </div>
            <label class="inline-flex items-center cursor-pointer">
                {% render_field form.match_command type="checkbox" class="sr-only peer" %}
                <div class="relative w-11 h-6 bg-gray-200 rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all  peer-checked:bg-purple-600 "></div>
            </label>
        </div>
    </div>
</div>


<button
    type="submit" 
    class="m-10 float-end text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-md text-sm px-5 py-2.5 text-center me-2 mb-2">
        Save preferences
</button>

</form>



{% include 'dashboard/ui/toast.html' %}

src/templates/dashboard/partials/billing_current_plan_info.html
<div class="font-grotesk">

   
    <h1 class="text-lg text-white pt-5 font-medium">
        Your subscription |
        <a href="{{customer_portal}}" target="_blank" class="text-purple-400 inline-flex items-center underline ">
            Manage
            <svg height="21" viewBox="0 0 21 21" width="21" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" transform="translate(6 6)"><path d="m8.5 7.5v-7h-7"/><path d="m8.5.5-8 8"/></g></svg>
        </a>
    </h1>
    
    
    

    <div class="flex flex-col md:flex-row justify-between py-5">
        <h2 class="text-gray-200 font-bold">Current Plan</h2>
        <p class="text-gray-200">{{request.user.get_billing_plan_display}}</p>
    </div>
    <hr class="border-zinc-800 ">
    <div class="flex flex-col md:flex-row justify-between py-5">
        <h2 class="text-gray-200 font-bold">Usage to date</h2>
        <p class="text-gray-200">{{quantity}} runs</p>
    </div>
    <hr class="border-zinc-800 ">
    <div class="flex flex-col md:flex-row justify-between py-5">
        <h2 class="text-gray-200 font-bold">Next bill</h2>
        <p class="text-gray-200">{{period_end|date:"F d, Y"}}</p>
    </div>
    
</div>

src/templates/dashboard/partials/free_trial_usage.html
{% with usage_limit=request.user.max_free_runs %}

<div class="flex flex-col gap-2 border border-zinc-800 p-5 rounded-lg transition duration-150 text-gray-200">
    <div class="flex justify-between font-grotesk font-medium">
        <h1>Free trial usage</h1>
        <p>{{used}}/{{usage_limit}}</p>
    </div>
    <div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
        <div class="bg-purple-600 h-2.5 rounded-full dark:bg-purple-500" style="width: {% if used > usage_limit%}100%{%else%}{% widthratio used usage_limit 100 %}%{%endif%}"></div>
    </div>
    
    {% if not hide_cta %}
        {% if used >= usage_limit %}
        <a
        href="{%url 'dashboard:billing' %}" 
        class="w-full mt-5 text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-md text-sm px-5 py-2.5 text-center me-2 mb-2">
            Upgrade
        </a>
        {%else%}
        <a href="{%url 'dashboard:billing' %}" class="text-sm underline text-gray-300 cursor-pointer">Unlock unlimited requests by upgrading to the creator plan</a>
        {% endif %}
    {% endif %}
  
</div>
{% endwith %}

src/templates/dashboard/partials/header.html
{%url 'dashboard:overview' as overview%}
{%url 'dashboard:alert-preferences' as preferences%}
{%url 'dashboard:billing' as billing%}

<div class="flex flex-col-reverse md:flex-row justify-between md:items-center">
    
    <div class="flex flex-col gap-5">
        <h1 class="text-3xl font-grotesk text-white ">Welcome {{request.user}}</h1>

        <nav class="flex p-1 items-center gap-2 bg-zinc-800 rounded-md w-fit" aria-label="Tabs">
            <a
            href="{{overview}}"
            class="{%if request.get_full_path == overview %}shrink-0 font-medium text-xs py-1.5 px-3 bg-zinc-950 text-white rounded-lg{%else%}shrink-0 font-medium text-xs py-1.5 px-3 text-gray-400{%endif%}"
            >
            Overview
            </a>
  
            <a
            href="{{preferences}}"
            class="{%if request.get_full_path == preferences %}shrink-0 font-medium text-xs py-1.5 px-3 bg-zinc-950 text-white rounded-lg{%else%}shrink-0 font-medium text-xs py-1.5 px-3 text-gray-400{%endif%}"
            aria-current="page"
            >
            Preferences
            </a>
            
            <a
            href="{{billing}}"
            class="{%if request.get_full_path == billing %}shrink-0 font-medium text-xs py-1.5 px-3 bg-zinc-950 text-white rounded-lg{%else%}shrink-0 font-medium text-xs py-1.5 px-3 text-gray-400{%endif%}"
            aria-current="page"
            >
            Account Settings
            </a>
            
        </nav>
  
    </div>

    
    <div class="flex">

        <button id="dropdownUserAvatarButton" data-dropdown-toggle="dropdownAvatar" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" type="button">
            <span class="sr-only">Open user menu</span>
            {% if request.user.socialaccount_set.first.extra_data.profile_image_url %}
            <img class="w-10 md:w-12 h-10 md:h-12 rounded-full" src="{{request.user.socialaccount_set.first.extra_data.profile_image_url}}" alt="">
            {% else %}
            <svg class="w-10 md:w-12 h-10 md:h-12 rounded-full" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
            {% endif %}
        </button>
        
        <!-- Dropdown menu -->
        <div id="dropdownAvatar" class="z-10 hidden  divide-y  rounded-lg shadow w-44 bg-zinc-900 divide-zinc-600">
            <div class="px-4 py-3 text-sm text-white">
            <div>{{request.user.username}}</div>
            <div class="font-medium truncate">{{request.user.email}}</div>
            </div>
            <ul class="py-2 text-sm text-zinc-400" aria-labelledby="dropdownUserAvatarButton">
            <li>
                <a href="{{overview}}" class="block px-4 py-2 hover:bg-zinc-800 hover:text-white">Overview</a>
            </li>
            <li>
                <a href="{{preferences}}" class="block px-4 py-2 hover:bg-zinc-800 hover:text-white">Preferences</a>
            </li>
            
            <li>
                <a href="{{billing}}" class="block px-4 py-2 hover:bg-zinc-800 hover:text-white">Settings</a>
            </li>
            
            </ul>
            <div class="py-2">
                <form method="POST" action="{% url 'account_logout' %}">
                    {%csrf_token%}
                    <button type="submit" class="flex w-full px-4 py-2 text-sm text-red-300 hover:bg-zinc-800 hover:text-red-600">Sign out</button>
                </form>
            
            </div>
        </div>
        
    




    </div>

</div>

src/templates/dashboard/partials/log_card.html
<div 
hx-get="{% url 'dashboard:hx-get-log-details' cheer_log_id=cheer_log.id %}"
hx-target="#log-details"
hx-swap="innerHTML"
class="flex flex-col gap-2 border border-zinc-800 cursor-pointer  p-5 rounded-lg transition duration-150 " 
onclick="setActive(this)">

    <div class="flex justify-between">
        <div class="flex items-center">
            <img src="https://media.tenor.com/izJVS6Wb-lYAAAAi/bits.gif" class="w-5" alt="">
            <h2 class="font-grotesk font-medium">{{cheer_log.bits}}</h2>
        </div>
        
        {% if cheer_log.status == failed_status %}
        <div class="flex items-center gap-1 font-grotesk">
            <span class="w-2.5 h-2.5 bg-red-400 rounded-full"></span> 
            <p>Failed</p>
        </div>
        {% elif cheer_log.status == done_status %}
        <div class="flex items-center gap-1 font-grotesk">
            <span class="w-2.5 h-2.5 bg-emerald-400 rounded-full"></span> 
            <p>Done</p>
        </div>
        {% elif cheer_log.status == ignored_status %}
        <div class="flex items-center gap-1 font-grotesk">
            <span class="w-2.5 h-2.5 bg-amber-400 rounded-full"></span> 
            <p>Ignored</p>
        </div>
        {% else %}
        <div class="flex items-center gap-1 font-grotesk">
            <span class="w-2.5 h-2.5 bg-blue-400 rounded-full"></span> 
            <p>New</p>
        </div>
        {% endif %}
    </div>
    
    <h2 class="font-grotesk text-white text-lg">{{cheer_log.user_name}}</h2>
    <p class="font-work text-gray-300">Input: {{cheer_log.message}}.</p>
    <span class="text-sm font-work text-gray-400">{{cheer_log.timestamp|date:"F d, Y"}}</span>
</div>
    

src/templates/dashboard/partials/log_details.html
<div class="flex flex-col gap-2 sticky top-10 border bg-zinc-950 border-zinc-800 text-gray-200 rounded-lg p-5">

    <div class="flex justify-between">
        <div class="flex items-center gap-1 font-grotesk">
            <h2 class="text-lg text-white">{{cheer_log.user_name}}</2>
        </div>
        <div class="flex items-center">
            <img src="https://media.tenor.com/izJVS6Wb-lYAAAAi/bits.gif" class="w-5" alt="">
            <h2 class="font-grotesk font-medium">{{cheer_log.bits}}</h2>
        </div>    
    </div>

    <p class="font-work text-gray-300">Input: {{cheer_log.message}}</p>

    <div 
    id="sfx-request-list" 
    class="flex flex-col gap-2"
    hx-get="{% url 'dashboard:hx-sfx-list-for-cheer-log' cheer_log_id=cheer_log.id %}" 
    hx-trigger="every 5s"
    hx-swap="innerHTML">
        
        {% include "dashboard/partials/sfx_control_list.html" with sfx_list=cheer_log.soundeffectrequest_set.all %}
        
    </div>


    <form 
    class="flex w-full"
    hx-target="#sfx-request-list"
    hx-swap="beforeend"
    hx-post="{% url 'dashboard:hx-generate-sfx' %}">
    <input type="hidden" name="cheer_log_id" value="{{cheer_log.id}}">
        <button
        type="submit" 
        class=" flex flex-row justify-center items-center w-full text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-md text-sm px-5 py-2.5 text-center me-2 mb-2">
            
        {% include "dashboard/ui/icons/generate_music.html" %}
        Generate again
        </button>
    </form>


</div>

src/templates/dashboard/partials/sfx_control.html
{% if sfx.status == done_status %}
<media-controller audio class="bg-transparent">
    <audio
    slot="media"
    src="{{sfx.generated_file.url}}"
    crossorigin
    >
    </audio>
    <media-control-bar class="flex justify-between border border-zinc-800 rounded-md items-center">
    
        <div class="align-middle">
            <media-play-button class="bg-transparent"></media-play-button>
            <media-time-display class="bg-transparent m-0 p-0"></media-time-display>
            <span>:</span>
            <media-duration-display class="bg-transparent m-0 p-0"></media-duration-display>
        </div>
        <div class="inline-flex items-center cursor-pointer">
            <svg class="w-5 h-5" viewBox="0 0 21 21"  xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" transform="translate(1 2)"><path d="m.5 7 16-6.535-2.8 14.535z"/><path d="m16.5.5-11 10"/><path d="m5.5 10.5v5l3-3"/></g></svg></span>
            <span 
            hx-get="{% url 'dashboard:hx-send-sfx-to-consumers' sfx_request_id=sfx.id %}" 
            hx-swap="none"
            class="text-sm px-2">
            
                Play on stream
            </span>

        </div>
    </media-control-bar>
</media-controller>
{% elif sfx.status == failed_status %}

<div class="p-2 py-3 w-full text-sm text-red-400 border border-red-400 rounded-md">
    <p>Failed reason: {{sfx.failed_reason}}</p>
</div>
{%endif%}

src/templates/dashboard/partials/sfx_control_list.html
{% for sfx in sfx_list %}

{% if sfx.status == done_status %}
<media-controller audio class="bg-transparent">
    <audio
    slot="media"
    src="{{sfx.generated_file.url}}"
    crossorigin
    >
    </audio>
    <media-control-bar class="flex justify-between border border-zinc-800 rounded-md items-center">
    
        <div class="align-middle">
            <media-play-button class="bg-transparent"></media-play-button>
            <media-time-display class="bg-transparent m-0 p-0"></media-time-display>
            <span>:</span>
            <media-duration-display class="bg-transparent m-0 p-0"></media-duration-display>
        </div>
        <div class="inline-flex items-center cursor-pointer">
            <svg class="w-5 h-5" viewBox="0 0 21 21"  xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" transform="translate(1 2)"><path d="m.5 7 16-6.535-2.8 14.535z"/><path d="m16.5.5-11 10"/><path d="m5.5 10.5v5l3-3"/></g></svg></span>
            <span 
            hx-get="{% url 'dashboard:hx-send-sfx-to-consumers' sfx_request_id=sfx.id %}" 
            hx-swap="none"
            class="text-sm px-2">
            
                Play on stream
            </span>

        </div>
    </media-control-bar>
</media-controller>
{% elif sfx.status == failed_status %}

<div class="p-2 py-3 w-full text-sm text-red-400 border border-red-400 rounded-md">
    <p>Failed reason: {{sfx.failed_reason}}</p>
</div>


{%endif%}

{% endfor %}